keycloak:
  realm: BANBEIS
  resource: next-client
  auth-server-url: http://localhost:8000/auth
  #credentials:
  #  secret: 036aa128-c882-4c8e-b210-69130f76e201
  public-client: true
  use-resource-role-mappings: true
  principal-attribute: sub
  cors: true


# ROLE BASED AUTH

#keycloak.security-constraints[0].authRoles[0]=relam_role
#keycloak.security-constraints[0].authRoles[1]=student
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/students/*
#
#keycloak.security-constraints[1].authRoles[0]=teacher
#keycloak.security-constraints[1].securityCollections[0].patterns[0]=/teacher/*




keycloak-user-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
#spring:
#  autoconfigure:
#   exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
