keycloak:
  realm: BANBEIS
  resource: spring-client
  auth-server-url: http://localhost:8000/auth
  credentials:
    secret: 036aa128-c882-4c8e-b210-69130f76e201

keycloak-user-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo

